version: 2

sources:
  - name: transactions_db
    database: transactions_db
    schema: default
    tables:
      - name: transactions
        description: Raw transactions dataset loaded from ClickHouse
        columns:
          - name: transaction_time
            description: Timestamp of transaction
          - name: merch
            description: Merchant identifier
          - name: cat_id
            description: Transaction category ID
          - name: amount
            description: Transaction amount
          - name: name_1
            description: Customer first name
          - name: name_2
            description: Customer last name
          - name: gender
            description: Customer gender (M/F)
          - name: street
            description: Customer street address
          - name: one_city
            description: Customer city
          - name: us_state
            description: Customer state
          - name: post_code
            description: Postal code
          - name: lat
            description: Customer latitude
          - name: lon
            description: Customer longitude
          - name: population_city
            description: Population of the city
          - name: jobs
            description: Customer job
          - name: merchant_lat
            description: Merchant latitude
          - name: merchant_lon
            description: Merchant longitude
          - name: target
            description: Fraud flag (0 or 1)
            tests:
              - accepted_values:
                  values: [0, 1]
